name: finalconectcon
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  barras: ^0.0.2 # QRCode Reader
  qr_flutter: ^4.0.0 # QRCode creator
  flutter_widget_from_html:  # html parser 
  share: ^2.0.1 # share to wpp/facebook/email...
  smooth_star_rating: ^1.1.1 # rating stars
  clipboard: ^0.1.3 # save string on clipboard
  charts_flutter: ^0.10.0 # graphics
  pull_to_refresh: ^1.6.4 # refresh screen
  get: ^4.1.1 # GetX
  get_storage: ^2.0.1 # GetX Storage
  line_awesome_flutter: ^1.0.1 # Icons
  system_settings: ^2.0.0 # entering in phone settings
  # google_fonts: ^2.0.0 # fontStyle
  pinch_zoom: ^0.1.0 # Dynamic zoom
  hive: ^2.0.1 # LocalStorage
  hive_flutter: ^1.0.0 # extension
  responsive_builder: ^0.4.1 # Responsive screens
  modal_progress_hud: ^0.1.3 # Loading action
  path_provider: ^2.0.1 # Provider
  provider: ^5.0.0 # Extension
  bot_toast: ^4.0.1 # Toasts
  image_picker: ^0.7.3 # Camera/Gallery photos
  flutter_web_browser: ^0.14.0 # Open in-App Browser
  diacritic: ^0.1.3 # Remove special characterees
  countdown_flutter: ^0.1.2 # Dynamic counter
  shared_preferences: ^2.0.5 # Simple Data storage
  firebase_messaging: ^9.1.0 # FireBase Notification
  device_info: ^2.0.0 # Get device information
  uuid: ^3.0.3 # Device UUID
  http: ^0.13.1 # API
  dropdown_search: ^0.5.0 # Searchable DropDown
  dropdownfield: ^1.0.3 # Custom Drop
  plain_notification_token: ^0.0.1
  splashscreen: ^1.3.5
  progress_indicators: ^1.0.0
  flutter_html:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0 # Laucher Icon
  hive_generator: ^1.0.1 
  build_runner: ^1.12.2
  flutter_native_splash: ^1.1.5+1

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon.png"

flutter_native_splash:
  image: assets/Loading.gif
  color: ffffff
  android_disable_fullscreen: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon.png
    - assets/icon.laucher.png
    - assets/Loading.gif
    - assets/silhueta20.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
